buildscript {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.7.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.20"
        classpath "dev.rikka.tools.refine:gradle-plugin:4.7.0"
        classpath "dev.rikka.tools:autoresconfig:1.4.0"
        classpath "dev.rikka.tools:materialthemebuilder:1.4.0"
    }
}

allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        google()
        mavenCentral()
    }
}

ext {
    versionCode = 100
    versionName = "1.0.0"
}
