import java.nio.file.Paths
import com.android.build.gradle.internal.tasks.CompileArtProfileTask

plugins {
    id('com.android.application')
    id('org.jetbrains.kotlin.android')
    id('dev.rikka.tools.refine')
    id('dev.rikka.tools.autoresconfig')
    id('dev.rikka.tools.materialthemebuilder')
}

android {
    namespace 'moe.shizuku.manager'
    defaultConfig {
        applicationId = "com.miaozuku.manager"
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=none'
            }
        }
    }
    buildFeatures {
        buildConfig true
        viewBinding true
        prefab true
    }
    signingConfigs {
        sign
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.sign
            zipAlignEnabled true
        }
        release {
            signingConfig signingConfigs.sign
            minifyEnabled true
            shrinkResources true
            vcsInfo.include false
            proguardFiles 'proguard-rules.pro'
        }
    }
    aaptOptions {
        noCompress "resources.arsc"
    }
    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
            version = "3.31.0+"
        }
    }
    kotlinOptions {
        jvmTarget = "21"
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging true
        }
        resources {
            excludes += ['**']
        }
    }
    dependenciesInfo {
        includeInApk false
    }
    lint {
        checkReleaseBuilds false
    }
}
