name: Build Miaozuku APK
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Shizuku Manager Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # 改成通配符匹配所有apk，解决找不到文件问题
      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: Shizuku-DebugAPK
          path: |
  manager/build/outputs/apk/debug/*.apk
  shell/build/outputs/apk/debug/*.apk
  starter/build/outputs/apk/debug/*.apk
