name: Build Miaozuku APK
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Shizuku Manager Debug APK
        run: ./gradlew :manager:assembleDebug --stacktrace

      - name: List Android SDK build tools
        run: ls $ANDROID_HOME/build-tools/

      - name: Zipalign 4-byte align APK
        run: |
          BUILD_TOOL_VER=$(ls $ANDROID_HOME/build-tools | tail -n1)
          $ANDROID_HOME/build-tools/$BUILD_TOOL_VER/zipalign -v 4 manager/build/outputs/apk/debug/manager-debug.apk manager/build/outputs/apk/debug/manager-debug-aligned.apk

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: Shizuku-DebugAPK
          path: manager/build/outputs/apk/debug/manager-debug-aligned.apk
