name: Build Miaozuku APK
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Shizuku Manager Release APK
        run: ./gradlew :manager:assembleRelease

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: Shizuku-ReleaseAPK
          path: manager/build/outputs/apk/release/manager-release-unsigned.apk
